import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./authProvider/Provider";
import Navbar from "./components/shared/Navbar";
import { Toaster } from "react-hot-toast";
import ProviderQuery from "./tanstackqueryProvider/QueryProvider";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Provider>
          <ProviderQuery>
            <Navbar />
            <Toaster />
            {children}
          </ProviderQuery>
        </Provider>

      </body>
    </html>
  );
}
